name: Deploy Flask App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy project to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "~/incident-management-system"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/incident-management-system
          python3 -m venv venv || true
          source venv/bin/activate
          pip install flask flask-sqlalchemy python-dotenv gunicorn boto3
          pkill gunicorn || true
          gunicorn app:app --bind 0.0.0.0:8000 --daemon